### ISSUE TITLE
Dependency was not found

### ISSUE THREAD

**Issue by biapar** [xmodulus/mdash#4]
$ vue-cli-service serve --mode development --dashboard
 INFO  Starting development server...

 89% module assets processing ERROR  Failed to compile with 1 errors21:46:43

This dependency was not found:

* -!../node_modules/css-loader/index.js??ref--8-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--8-oneOf-1-2!../../../node_modules/bulma-extensions/dist/css/bulma-extensions.min.css in ./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--8-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss&

To install it, you can run: npm install --save -!../node_modules/css-loader/index.js??ref--8-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--8-oneOf-1-2!../../../node_modules/bulma-extensions/dist/css/bulma-extensions.min.css

**Comment by azizsafudin** [comment]
@biapar Bulma extensions has been finicky for some reason. Comment out [**this line**](https://github.com/xmodulus/mdash/blob/master/src/assets/css/global.scss#L12) to ignore it. I'm use that module just for the tooltips.
